// Mocks generated by Mockito 5.2.0 from annotations
// in rune/test/infrastructure/repositories/post_repository/post_repo_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rune/domain/models.dart' as _i2;
import 'package:rune/infrastructure/repositories.dart' as _i5;

import 'post_repo_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeExpect_0<T> extends _i1.Fake implements _i2.Expect<T> {}

/// A class which mocks [PostRepoTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepoTest extends _i1.Mock implements _i3.PostRepoTest {
  MockPostRepoTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Expect<List<_i2.Post>>> getPosts(
          _i5.UserRepository? userRepository, int? chanId, int? page,
          [int? size]) =>
      (super.noSuchMethod(
          Invocation.method(#getPosts, [userRepository, chanId, page, size]),
          returnValue: Future<_i2.Expect<List<_i2.Post>>>.value(
              _FakeExpect_0<List<_i2.Post>>())) as _i4
          .Future<_i2.Expect<List<_i2.Post>>>);
  @override
  _i4.Future<_i2.Expect<_i2.Post>> createPost(
          _i5.UserRepository? userRepository,
          int? channelId,
          String? title,
          String? content) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createPost, [userRepository, channelId, title, content]),
              returnValue:
                  Future<_i2.Expect<_i2.Post>>.value(_FakeExpect_0<_i2.Post>()))
          as _i4.Future<_i2.Expect<_i2.Post>>);
  @override
  _i4.Future<_i2.Expect<_i2.Post>> votePost(
          _i5.UserRepository? userRepository, int? postId, String? type) =>
      (super.noSuchMethod(
              Invocation.method(#votePost, [userRepository, postId, type]),
              returnValue:
                  Future<_i2.Expect<_i2.Post>>.value(_FakeExpect_0<_i2.Post>()))
          as _i4.Future<_i2.Expect<_i2.Post>>);
}
